//go:build ignore

// Command gentables snapshots the Unicode letter/number classification and
// simple-lowercase mapping used by the word tokenizer into
// unicodetables.go, freezing them at the generating toolchain's Unicode
// version. This removes the tokenizer's dependence on the Go toolchain's
// Unicode tables: determinism is pinned to semblance's own committed data.
//
// Regenerating (go generate ./shingle) adopts a newer Unicode version and
// is a deliberate, signature-affecting event — review the golden diffs.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"unicode"
)

func main() {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by gentables.go; DO NOT EDIT.

// Frozen Unicode %s data for word-shingle tokenization: Letter-or-Number
// classification and simple lowercase mapping, for runes >= 0x80 (ASCII is
// handled by fast paths in shingle.go). Committing these decouples
// tokenization from the Go toolchain's Unicode version. Regenerate with
// "go generate ./shingle" only as a deliberate, signature-affecting change.

package shingle

import "unicode"

// UnicodeVersion is the Unicode version the frozen tokenizer tables were
// generated at. Word-shingle tokenization uses this data, not the Go
// toolchain's, so its output is stable regardless of the toolchain's own
// Unicode version.
const UnicodeVersion = %q

`, unicode.Version, unicode.Version)

	writeRangeTable(&buf, "tokenRunes", func(r rune) bool {
		return unicode.IsLetter(r) || unicode.IsNumber(r)
	})
	writeLowerTable(&buf, "lowerRunes")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprint(os.Stderr, buf.String())
		panic(err)
	}
	if err := os.WriteFile("unicodetables.go", src, 0o644); err != nil {
		panic(err)
	}
}

// writeRangeTable emits a *unicode.RangeTable covering the runes >= 0x80
// for which in reports true, split across R16/R32 at U+FFFF.
func writeRangeTable(buf *bytes.Buffer, name string, in func(rune) bool) {
	type rng struct{ lo, hi rune }
	var ranges []rng
	inRange := false
	var lo rune
	for r := rune(0x80); r <= unicode.MaxRune; r++ {
		switch {
		case in(r) && !inRange:
			lo, inRange = r, true
		case !in(r) && inRange:
			ranges = append(ranges, rng{lo, r - 1})
			inRange = false
		}
	}
	if inRange {
		ranges = append(ranges, rng{lo, unicode.MaxRune})
	}

	type r16 struct{ lo, hi uint16 }
	type r32 struct{ lo, hi uint32 }
	var lo16 []r16
	var lo32 []r32
	latinOffset := 0
	for _, rg := range ranges {
		if rg.lo <= 0xFFFF {
			hi := rg.hi
			if hi > 0xFFFF {
				hi = 0xFFFF
			}
			lo16 = append(lo16, r16{uint16(rg.lo), uint16(hi)})
			if hi <= unicode.MaxLatin1 {
				latinOffset++
			}
		}
		if rg.hi > 0xFFFF {
			start := rg.lo
			if start < 0x10000 {
				start = 0x10000
			}
			lo32 = append(lo32, r32{uint32(start), uint32(rg.hi)})
		}
	}

	fmt.Fprintf(buf, "var %s = &unicode.RangeTable{\n", name)
	fmt.Fprintf(buf, "R16: []unicode.Range16{\n")
	for _, e := range lo16 {
		fmt.Fprintf(buf, "{0x%04x, 0x%04x, 1},\n", e.lo, e.hi)
	}
	fmt.Fprintf(buf, "},\n")
	if len(lo32) > 0 {
		fmt.Fprintf(buf, "R32: []unicode.Range32{\n")
		for _, e := range lo32 {
			fmt.Fprintf(buf, "{0x%06x, 0x%06x, 1},\n", e.lo, e.hi)
		}
		fmt.Fprintf(buf, "},\n")
	}
	fmt.Fprintf(buf, "LatinOffset: %d,\n}\n\n", latinOffset)
}

// writeLowerTable emits the sorted simple-lowercase mapping for runes
// >= 0x80 that change under lowercasing.
func writeLowerTable(buf *bytes.Buffer, name string) {
	fmt.Fprintf(buf, "// %s maps runes >= 0x80 to their simple lowercase form, only where\n", name)
	fmt.Fprintf(buf, "// it differs, sorted by rune for binary search.\n")
	fmt.Fprintf(buf, "var %s = []lowerEntry{\n", name)
	for r := rune(0x80); r <= unicode.MaxRune; r++ {
		if lo := unicode.ToLower(r); lo != r {
			fmt.Fprintf(buf, "{0x%04x, 0x%04x},\n", r, lo)
		}
	}
	fmt.Fprintf(buf, "}\n")
}
